### ISSUE TITLE
"docker-compose up -d" error

### ISSUE THREAD

**Issue by fmarkos** [mrfoh/docker-laravel#1]
Setup: 
Windows 7 64bit, 
docker 17.04.0 
docker-composer (installed with pip install docker-compose )

when I run "docker-compose up -d" I get:
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in ".\docker-compose.yml", line 27, column 18

**Comment by mrfoh** [comment]
@fmarkos Hello can your post your docker-compose here?

**Comment by milanchheda** [comment]
I am getting the same error too :( 
Below is the screenshot:

<img width="563" alt="screen shot 2017-05-01 at 17 20 41" src="https://cloud.githubusercontent.com/assets/1329515/25580515/a20cbfe2-2e92-11e7-882e-a5c10f899bc7.png">

**Comment by mrfoh** [comment]
Hello @milanchheda and @fmarkos, I've updated the docker-compose file with my last commit. It will resolve this issue, please pull the repo and provide feedback so we can close this issue.

**Comment by mrfoh** [comment]
```
version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    links:
      - db
    environment:
      - DB_PORT=3306
      - DB_HOST=db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dockerApp
    ports:
      - "33061:3306"
```
